enabled: true
auto_sync_draft: false
auto_sync_ready: true
additional_vetters:
  - abhishek-ak-nv
  - akshayanv
  - ary1111
  - ashan-nv
  - ashwind-nvidia
  - asonny02
  - ayyappa-dev
  - banose
  - danh-nguyen-nvidia
  - daviddu0425
  - dineshv
  - dsitlani-nv
  - freshyjmp
  - giapdq
  - gous-75
  - harshalnishar
  - hfarooq-nv
  - hntran-nvidia
  - hugoverjus
  - huyprowow
  - jiayin-nvidia
  - kaushikc-nvidia
  - lebahoang
  - lianqiann
  - liamy-nv
  - mansiigo
  - munjalp6
  - nathankw
  - nikunj-jesadiya
  - nv-mpandele
  - nv-pnikam
  - nv-vankit
  - nv-zhliu
  - peterychang
  - poojavenkatesan
  - pratik-bhatt-nv
  - prisrivastav-nv
  - rahul3349
  - romalakar
  - shubham050300
  - soumilinandi
  - ssmmoo1
  - trongp-nvidia
  - vineet-raina
  - vishkumar56
  - zac-wang-nv
  - gbau1
  - alexzh-nvda
