# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ext.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'schema_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ext.proto", :syntax => :proto3) do
    add_message "nv.GeoLocation" do
      optional :type, :string, 1
      repeated :coordinates, :message, 2, "nv.GeoLocation.Point"
    end
    add_message "nv.GeoLocation.Point" do
      repeated :point, :double, 1
    end
    add_message "nv.Behavior" do
      optional :id, :string, 1
      optional :timestamp, :message, 2, "google.protobuf.Timestamp"
      optional :end, :message, 3, "google.protobuf.Timestamp"
      optional :locations, :message, 5, "nv.GeoLocation"
      optional :smoothLocations, :message, 6, "nv.GeoLocation"
      repeated :edges, :string, 7
      optional :distance, :double, 8
      optional :speed, :double, 9
      repeated :speedOverTime, :double, 10
      optional :timeInterval, :double, 11
      optional :bearing, :double, 12
      optional :direction, :string, 13
      optional :length, :int32, 14
      optional :place, :message, 15, "nv.Place"
      optional :sensor, :message, 16, "nv.Sensor"
      optional :analyticsModule, :message, 17, "nv.AnalyticsModule"
      optional :object, :message, 18, "nv.Object"
      optional :event, :message, 19, "nv.Event"
      optional :videoPath, :string, 20
      repeated :poses, :message, 21, "nv.Pose"
      repeated :lipActivities, :message, 22, "nv.LipActivity"
      repeated :gazes, :message, 23, "nv.Gaze"
      repeated :embeddings, :message, 24, "nv.Embedding"
      optional :llm, :message, 26, "nv.LLM"
      map :info, :string, :string, 25
    end
    add_message "nv.Incident" do
      optional :sensorId, :string, 1
      optional :timestamp, :message, 2, "google.protobuf.Timestamp"
      optional :end, :message, 3, "google.protobuf.Timestamp"
      repeated :objectIds, :string, 4
      repeated :frameIds, :string, 5
      optional :place, :message, 6, "nv.Place"
      optional :analyticsModule, :message, 7, "nv.AnalyticsModule"
      optional :category, :string, 8
      repeated :embeddings, :message, 9, "nv.Embedding"
      optional :isAnomaly, :bool, 10
      optional :llm, :message, 12, "nv.LLM"
      map :info, :string, :string, 11
    end
    add_message "nv.SpaceUtilizationMetrics" do
      optional :spaceOccupied, :double, 1
      optional :freeSpace, :double, 2
      optional :totalSpace, :double, 3
      optional :spaceUtilization, :double, 4
      optional :numExtraPallets, :int32, 5
      optional :utilizableFreeSpace, :double, 6
      optional :freeSpaceQuality, :double, 7
      optional :isUnsafe, :bool, 8
    end
    add_message "nv.SpaceUtilizationLayouts" do
      repeated :freeSpace, :message, 1, "nv.Polygon"
      repeated :utilizableFreeSpace, :message, 2, "nv.Polygon"
    end
    add_message "nv.SpaceUtilization" do
      optional :id, :string, 1
      optional :timestamp, :message, 2, "google.protobuf.Timestamp"
      optional :metrics, :message, 3, "nv.SpaceUtilizationMetrics"
      repeated :sensors, :string, 4
      optional :layouts, :message, 5, "nv.SpaceUtilizationLayouts"
    end
  end
end

module Nv
  GeoLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.GeoLocation").msgclass
  GeoLocation::Point = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.GeoLocation.Point").msgclass
  Behavior = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Behavior").msgclass
  Incident = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Incident").msgclass
  SpaceUtilizationMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.SpaceUtilizationMetrics").msgclass
  SpaceUtilizationLayouts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.SpaceUtilizationLayouts").msgclass
  SpaceUtilization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.SpaceUtilization").msgclass
end
