# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("schema.proto", :syntax => :proto3) do
    add_message "nv.Frame" do
      optional :version, :string, 1
      optional :id, :string, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
      optional :sensorId, :string, 4
      repeated :objects, :message, 5, "nv.Object"
      repeated :fov, :message, 6, "nv.TypeMetrics"
      repeated :rois, :message, 7, "nv.TypeMetrics"
      optional :socialDistancing, :message, 8, "nv.SD"
      optional :segmentation, :message, 9, "nv.Segmentation"
      repeated :interactions, :message, 10, "nv.Interaction"
      repeated :congestions, :message, 11, "nv.Congestion"
      map :info, :string, :string, 12
    end
    add_message "nv.Object" do
      optional :id, :string, 1
      optional :bbox, :message, 2, "nv.Bbox"
      optional :type, :string, 3
      optional :confidence, :float, 4
      map :info, :string, :string, 5
      optional :embedding, :message, 6, "nv.Embedding"
      optional :pose, :message, 7, "nv.Pose"
      optional :gaze, :message, 8, "nv.Gaze"
      optional :lipActivity, :message, 9, "nv.LipActivity"
      optional :speed, :float, 10
      repeated :dir, :float, 11
      optional :coordinate, :message, 12, "nv.Coordinate"
      optional :location, :message, 13, "nv.Location"
      optional :bbox3d, :message, 14, "nv.Bbox3d"
    end
    add_message "nv.Coordinate" do
      optional :x, :double, 1
      optional :y, :double, 2
      optional :z, :double, 3
    end
    add_message "nv.Location" do
      optional :lat, :double, 1
      optional :lon, :double, 2
      optional :alt, :double, 3
    end
    add_message "nv.Bbox" do
      optional :leftX, :float, 1
      optional :topY, :float, 2
      optional :rightX, :float, 3
      optional :bottomY, :float, 4
      repeated :embeddings, :message, 5, "nv.Embedding"
      optional :confidence, :float, 6
      map :info, :string, :string, 7
    end
    add_message "nv.Bbox3d" do
      repeated :coordinates, :double, 1
      repeated :embeddings, :message, 2, "nv.Embedding"
      optional :confidence, :float, 3
      map :info, :string, :string, 4
    end
    add_message "nv.Segmentation" do
      repeated :mask, :int32, 1
      map :info, :string, :string, 2
    end
    add_message "nv.TypeMetrics" do
      optional :id, :string, 1
      optional :type, :string, 2
      optional :count, :int32, 3
      repeated :coordinates, :message, 4, "nv.Coordinate"
      repeated :objectIds, :string, 5
      map :info, :string, :string, 6
    end
    add_message "nv.Cluster" do
      repeated :points, :message, 1, "nv.Point2D"
    end
    add_message "nv.Point2D" do
      optional :x, :double, 1
      optional :y, :double, 2
    end
    add_message "nv.SD" do
      optional :threshold, :double, 1
      optional :proximityDetections, :int32, 2
      repeated :clusters, :message, 3, "nv.Cluster"
      map :info, :string, :string, 4
    end
    add_message "nv.Polygon" do
      repeated :coordinates, :message, 1, "nv.Point2D"
      repeated :holes, :message, 2, "nv.PolygonHole"
    end
    add_message "nv.PolygonHole" do
      repeated :coordinates, :message, 1, "nv.Point2D"
    end
    add_message "nv.Interaction" do
      optional :id, :string, 1
      repeated :objectIds, :string, 2
      repeated :coordinates, :message, 3, "nv.Coordinate"
      optional :description, :string, 4
      map :info, :string, :string, 5
    end
    add_message "nv.Congestion" do
      optional :id, :string, 1
      repeated :objectIds, :string, 2
      optional :amount, :float, 3
      map :info, :string, :string, 4
    end
    add_message "nv.Pose" do
      optional :type, :string, 1
      repeated :keypoints, :message, 2, "nv.Pose.Keypoint"
      repeated :actions, :message, 3, "nv.Pose.Action"
      map :info, :string, :string, 4
    end
    add_message "nv.Pose.Keypoint" do
      optional :name, :string, 1
      repeated :coordinates, :float, 2
      repeated :quaternion, :float, 3
    end
    add_message "nv.Pose.Action" do
      optional :type, :string, 1
      optional :confidence, :float, 2
    end
    add_message "nv.Gaze" do
      optional :x, :float, 1
      optional :y, :float, 2
      optional :z, :float, 3
      optional :theta, :float, 4
      optional :phi, :float, 5
    end
    add_message "nv.LipActivity" do
      optional :classLabel, :string, 1
    end
    add_message "nv.Event" do
      optional :id, :string, 1
      optional :type, :string, 2
      map :info, :string, :string, 5
    end
    add_message "nv.AnalyticsModule" do
      optional :id, :string, 1
      optional :description, :string, 2
      optional :source, :string, 3
      optional :version, :string, 4
      map :info, :string, :string, 5
    end
    add_message "nv.Sensor" do
      optional :id, :string, 1
      optional :type, :string, 2
      optional :description, :string, 3
      optional :location, :message, 4, "nv.Location"
      optional :coordinate, :message, 5, "nv.Coordinate"
      map :info, :string, :string, 6
    end
    add_message "nv.Place" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
      optional :location, :message, 4, "nv.Location"
      optional :coordinate, :message, 5, "nv.Coordinate"
      map :info, :string, :string, 6
    end
    add_message "nv.Message" do
      optional :messageid, :string, 1
      optional :mdsversion, :string, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
      optional :place, :message, 4, "nv.Place"
      optional :sensor, :message, 5, "nv.Sensor"
      optional :analyticsModule, :message, 6, "nv.AnalyticsModule"
      optional :object, :message, 7, "nv.Object"
      optional :event, :message, 8, "nv.Event"
      optional :videoPath, :string, 9
    end
    add_message "nv.Embedding" do
      repeated :vector, :float, 1
      map :info, :string, :string, 2
    end
    add_message "nv.ImageData" do
      optional :format, :enum, 1, "nv.ImageFormat"
      optional :encoding, :string, 2
      optional :name, :string, 3
      optional :data, :bytes, 4
      map :info, :string, :string, 5
    end
    add_message "nv.VisionLLM" do
      optional :version, :string, 1
      optional :timestamp, :message, 2, "google.protobuf.Timestamp"
      optional :end, :message, 3, "google.protobuf.Timestamp"
      optional :startFrameId, :string, 4
      optional :endFrameId, :string, 5
      optional :sensor, :message, 6, "nv.Sensor"
      optional :llm, :message, 7, "nv.LLM"
      map :info, :string, :string, 8
    end
    add_message "nv.LLM" do
      map :info, :string, :string, 1
      repeated :queries, :message, 2, "nv.Query"
      repeated :visionEmbeddings, :message, 3, "nv.Embedding"
    end
    add_message "nv.Query" do
      optional :id, :string, 1
      map :params, :string, :string, 2
      map :prompts, :string, :string, 3
      optional :response, :string, 4
      repeated :embeddings, :message, 5, "nv.Embedding"
    end
    add_enum "nv.ImageFormat" do
      value :RAW, 0
      value :JPG, 1
      value :JPEG, 2
      value :PNG, 3
    end
  end
end

module Nv
  Frame = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Frame").msgclass
  Object = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Object").msgclass
  Coordinate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Coordinate").msgclass
  Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Location").msgclass
  Bbox = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Bbox").msgclass
  Bbox3d = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Bbox3d").msgclass
  Segmentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Segmentation").msgclass
  TypeMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.TypeMetrics").msgclass
  Cluster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Cluster").msgclass
  Point2D = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Point2D").msgclass
  SD = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.SD").msgclass
  Polygon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Polygon").msgclass
  PolygonHole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.PolygonHole").msgclass
  Interaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Interaction").msgclass
  Congestion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Congestion").msgclass
  Pose = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Pose").msgclass
  Pose::Keypoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Pose.Keypoint").msgclass
  Pose::Action = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Pose.Action").msgclass
  Gaze = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Gaze").msgclass
  LipActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.LipActivity").msgclass
  Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Event").msgclass
  AnalyticsModule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.AnalyticsModule").msgclass
  Sensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Sensor").msgclass
  Place = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Place").msgclass
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Message").msgclass
  Embedding = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Embedding").msgclass
  ImageData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.ImageData").msgclass
  VisionLLM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.VisionLLM").msgclass
  LLM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.LLM").msgclass
  Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.Query").msgclass
  ImageFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nv.ImageFormat").enummodule
end
