# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
  - path: ./video-analytics-2d-app/compose.yml
services:
  kibana-init-container-search:
    build:
      context: $MDX_SAMPLE_APPS_DIR/developer-workflow/dev-profile-search
      dockerfile: $MDX_SAMPLE_APPS_DIR/developer-workflow/dev-profile-search/Dockerfiles/kibana-dashboard.Dockerfile
      network: "host"
    network_mode: "host"
    profiles: ["bp_developer_search_2d"]
    container_name: mdx-kibana-init-search
    command: bash /opt/mdx/init-scripts/kibana-import-dashboard.sh
    depends_on:
      kibana:
        condition: service_healthy