# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  kibana-init-container-lvs:
    build:
      context: $MDX_SAMPLE_APPS_DIR/developer-workflow/dev-profile-lvs
      dockerfile: $MDX_SAMPLE_APPS_DIR/developer-workflow/dev-profile-lvs/Dockerfiles/kibana-dashboard.Dockerfile
    network_mode: "host"
    profiles: ["bp_developer_lvs_2d"]
    container_name: mdx-kibana-init-lvs
    command: bash /opt/mdx/init-scripts/kibana-import-dashboard.sh
    restart: on-failure