# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:

  phoenix:
    container_name: phoenix
    image: 'arizephoenix/phoenix:version-8.12.1'
    profiles: ["bp_wh_2d","bp_smc_2d","bp_ps_2d","bp_developer_base_2d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    environment:
      PHOENIX_WORKING_DIR: '/.phoenix/'
    volumes:
    - phoenix-data:/.phoenix
    ports:
    - 6006:6006

  elasticsearch:
    build:
      context: $MDX_SAMPLE_APPS_DIR/foundational
      dockerfile: Dockerfiles/elasticsearch.Dockerfile
      network: "host"
    image: elasticsearch
    network_mode: "host"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms256m"
      discovery.type: single-node
    profiles: ["bp_wh_2d","bp_wh_kafka_2d${MINIMAL_PROFILE:+_extended}","bp_wh_kafka_3d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_2d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_3d${MINIMAL_PROFILE:+_extended}","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    volumes:
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - mdx-elastic-data:/tmp/elastic/data:rw
      - mdx-elastic-logs:/tmp/elastic/logs:rw
    container_name: mdx-elastic
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  elasticsearch-init-container:
    build:
      context: $MDX_SAMPLE_APPS_DIR/foundational
      dockerfile: Dockerfiles/elastic-init.Dockerfile
      network: "host"
    profiles: ["bp_wh_2d","bp_wh_kafka_2d${MINIMAL_PROFILE:+_extended}","bp_wh_kafka_3d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_2d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_3d${MINIMAL_PROFILE:+_extended}","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    network_mode: "host"
    container_name: mdx-elasticsearch-init
    environment:
      - BP_PROFILE=${BP_PROFILE}
      - ELASTICSEARCH_CONNECTION_MAX_ATTEMPTS=${ELASTICSEARCH_CONNECTION_MAX_ATTEMPTS:-20}
      - ELASTICSEARCH_ILM_MIN_AGE=${ELASTICSEARCH_ILM_MIN_AGE:-4h}
      - ELASTICSEARCH_RTVI_CV_EMBEDDINGS_DIM=${ELASTICSEARCH_RTVI_CV_EMBEDDINGS_DIM:-1536}
      - ELASTICSEARCH_VISION_LLM_EMBEDDINGS_DIM=${ELASTICSEARCH_VISION_LLM_EMBEDDINGS_DIM:-768}
    command: bash -c "
      /opt/mdx/init-scripts/elasticsearch-ilm-policy-creation.sh &&
      /opt/mdx/init-scripts/elasticsearch-template-creation.sh &&
      /opt/mdx/init-scripts/elasticsearch-ingest-pipeline-creation.sh
      "
    depends_on:
      - elasticsearch

  kafka:
    image: confluentinc/cp-kafka:8.1.1
    network_mode: "host"
    volumes:
      - mdx-kafka:/tmp/kafka-data
      - $MDX_SAMPLE_APPS_DIR/foundational/kafka-entrypoint.sh:/usr/local/bin/kafka-entrypoint.sh:ro
    profiles: ["bp_wh_2d","bp_wh_kafka_2d","bp_wh_kafka_3d","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","bp_developer_search_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$HOST_IP:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx6G -Xms6G"
      KAFKA_MAX_REQUEST_SIZE: 10485760
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_MAX_PARTITION_FETCH_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_LOG_DIRS: '/tmp/kafka-data'
    container_name: mdx-kafka
    entrypoint: ["/bin/sh","/usr/local/bin/kafka-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "sh", "-c", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s

  kafka-topic-init-container:
    image: confluentinc/cp-kafka:8.1.1
    container_name: mdx-kafka-topics
    network_mode: "host"
    profiles: ["bp_wh_2d","bp_wh_kafka_2d","bp_wh_kafka_3d","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","bp_developer_search_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    volumes:
      - $MDX_SAMPLE_APPS_DIR/foundational/kafka/init-scripts/create-kafka-topics.sh:/usr/bin/create-kafka-topics.sh
    environment:
      DEFAULT_PARTITIONS: "8"
      DEFAULT_RETENTION_MS: "14400000"
      DEFAULT_SEGMENT_MS: "3600000"
      DEFAULT_REPLICATION_FACTOR: "1"
      BOOTSTRAP_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_TOPICS: '[{"name": "mdx-raw"},
        {"name": "mdx-bev"},
        {"name": "mdx-space-utilization"},
        {"name": "mdx-alerts"},
        {"name": "mdx-behavior", "retention_ms": "14400000", "segment_ms": "3600000", "replication_factor": "1"},
        {"name": "mdx-behavior-plus"},
        {"name": "mdx-frames"},
        {"name": "mdx-mtmc"},
        {"name": "mdx-rtls"},
        {"name": "mdx-rtls-region-1"},
        {"name": "mdx-amr"},
        {"name": "mdx-vlm-alerts"},
        {"name": "mdx-notification", "partitions": "1"},
        {"name": "mdx-events"},
        {"name": "mdx-incidents"},
        {"name": "mdx-vlm-incidents"},
        {"name": "mdx-vlm"},
        {"name": "mdx-embed"},
        {"name": "mdx-embed-filtered"}]'
    depends_on:
      kafka:
        condition: service_healthy
    command: "bash /usr/bin/create-kafka-topics.sh"  

  redis:
    image: redis:8.2.2-alpine
    profiles: ["bp_wh_2d","bp_wh_redis_2d","bp_wh_redis_3d","bp_wh_kafka_2d","bp_wh_kafka_3d","bp_smc_2d","bp_ps_2d","bp_developer_base_2d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    restart: always
    command: redis-server /config/redis.conf
    network_mode: host
    container_name: mdx-redis
    volumes:
      - $MDX_SAMPLE_APPS_DIR/foundational/redis/configs/redis.conf:/config/redis.conf
      - $MDX_DATA_DIR/data_log/redis/data:/data
      - $MDX_DATA_DIR/data_log/redis/log:/log

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.0
    network_mode: "host"
    profiles: ["bp_wh_2d","bp_wh_kafka_2d${MINIMAL_PROFILE:+_extended}","bp_wh_kafka_3d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_2d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_3d${MINIMAL_PROFILE:+_extended}","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    volumes:
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/configs/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      SERVER_PUBLICBASEURL: ${KIBANA_PUBLIC_URL:-http://localhost:5601}
      SERVER_SECURITYRESPONSEHEADERS_DISABLEEMBEDDING: "false"
      CSP_STRICT: "false"
    container_name: mdx-kibana
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s

  logstash:
    image: docker.elastic.co/logstash/logstash:9.3.0
    network_mode: "host"
    profiles: ["bp_wh_2d","bp_wh_kafka_2d${MINIMAL_PROFILE:+_extended}","bp_wh_kafka_3d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_2d${MINIMAL_PROFILE:+_extended}","bp_wh_redis_3d${MINIMAL_PROFILE:+_extended}","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    volumes:
      - mdx-logstash-libs:/opt/logstash-data-libs
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/pb_definitions/ruby/ext_pb.rb:/opt/logstash-data-libs/logstash/pb_definitions/ext_pb.rb
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/pb_definitions/ruby/schema_pb.rb:/opt/logstash-data-libs/logstash/pb_definitions/schema_pb.rb
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/pb_definitions/descriptors/ext.desc:/opt/logstash-data-libs/logstash/pb_definitions/descriptors/ext.desc
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/pb_definitions/descriptors/schema.desc:/opt/logstash-data-libs/logstash/pb_definitions/descriptors/schema.desc
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/configs/mdx-${STREAM_TYPE}-logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - $MDX_SAMPLE_APPS_DIR/foundational/elk/gems/logstash-input-redis_stream-3.1.0-java.gem:/usr/share/logstash/gems/logstash-redis-stream-input-java.gem
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms256m"
      STREAM_TYPE: ${STREAM_TYPE}
    container_name: mdx-logstash
    restart: always
    depends_on:
      broker-health-check:
        condition: service_completed_successfully
      elasticsearch-init-container:
        condition: service_completed_successfully
    command: >
      bash -c "
        echo 'Installing gems for mdx-apps.. This may take sometime to install plugins...' &&
        ls -al /opt/logstash-data-libs/ &&
        if [ \"$$STREAM_TYPE\" = 'redis' ]; then
          echo 'Installing Redis stream input plugin...' &&
          /usr/share/logstash/bin/logstash-plugin install /usr/share/logstash/gems/logstash-redis-stream-input-java.gem;
        elif [ \"$$STREAM_TYPE\" = 'kafka' ]; then
          echo 'Installing protobuf codec plugin...' &&
          /usr/share/logstash/bin/logstash-plugin install logstash-codec-protobuf;
        fi &&
        echo 'Installed gems for logstash plugins' &&
        /usr/local/bin/docker-entrypoint"

  
  broker-health-check:
    build:
      context: $MDX_SAMPLE_APPS_DIR/foundational
      dockerfile: Dockerfiles/${STREAM_TYPE}-health-check.Dockerfile
      network: host
    profiles: ["bp_wh_2d","bp_wh_redis_3d","bp_wh_redis_2d","bp_wh_kafka_2d","bp_wh_kafka_3d","bp_smc_2d","bp_ps_2d","playback_kafka_2d","playback_kafka_3d","playback_redis_2d","playback_redis_3d","bp_developer_search_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    network_mode: "host"
    environment:
      MAX_RETRIES: 60
      RETRY_INTERVAL: 2
      BOOTSTRAP_HOST: localhost
      KAFKA_PORT: 9092
      REDIS_PORT: 6379
      KAFKA_TOPICS: '[{"name": "mdx-raw"},
        {"name": "mdx-bev"},
        {"name": "mdx-space-utilization"},
        {"name": "mdx-alerts"},
        {"name": "mdx-behavior"},
        {"name": "mdx-behavior-plus"},
        {"name": "mdx-frames"},
        {"name": "mdx-mtmc"},
        {"name": "mdx-rtls"},
        {"name": "mdx-rtls-region-1"},
        {"name": "mdx-amr"},
        {"name": "mdx-vlm-alerts"},
        {"name": "mdx-notification"},
        {"name": "mdx-events"},
        {"name": "mdx-incidents"},
        {"name": "mdx-vlm-incidents"},
        {"name": "mdx-vlm"},
        {"name": "mdx-embed"},
        {"name": "mdx-embed-filtered"}]'
    container_name: mdx-broker-health-check
    restart: "no"

volumes:
  phoenix-data:
  mdx-logstash-libs:
  mdx-elastic-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $MDX_DATA_DIR/data_log/elastic/data
  mdx-elastic-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $MDX_DATA_DIR/data_log/elastic/logs
  mdx-kafka:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $MDX_DATA_DIR/data_log/kafka
